/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package YoneticiPaketi;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import main.Frm_giris;
//import personelizintakipyapp.Frm_giris;

/**
 *
 * @author scramblebit
 */
public class frm_YoneticilKayit extends javax.swing.JFrame {

    /**
     * Creates new form frm_KullaniciKayit
     */
   

    public frm_YoneticilKayit() {
        initComponents();
        try {
            
            Connection cn= DriverManager.getConnection("jdbc:derby://localhost:1527/personelIzinTakipi", "app", "app");
            Statement s=cn.createStatement();
             int id=0 ;
            ResultSet rs=s.executeQuery("SELECT * FROM YONETICI");
            while (rs.next()) {                
                if(id<rs.getInt("ID")){
                    id=rs.getInt("ID");
                }
            }
            lblID.setText(String.valueOf(++id));
        } catch (SQLException ex) {
            Logger.getLogger(frm_YoneticilKayit.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblID = new javax.swing.JLabel();
        txtTc = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtAdi = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtSifre1 = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        txtSifre2 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtSoyadi = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(lblID, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 40, 35));
        getContentPane().add(txtTc, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 151, 37));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText(" Ad");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 60, 106, 35));
        getContentPane().add(txtAdi, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 151, 37));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Şifre Oluşturun");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 106, 35));

        txtSifre1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSifre1ActionPerformed(evt);
            }
        });
        getContentPane().add(txtSifre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 151, 35));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Şifre Onaylayın");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 106, 35));

        txtSifre2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSifre2ActionPerformed(evt);
            }
        });
        getContentPane().add(txtSifre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 149, 35));

        jButton1.setText("IPTAL");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 98, -1));

        jButton2.setText("KAYDET");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 98, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Soyadı");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 106, 35));
        getContentPane().add(txtSoyadi, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 151, 37));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("TC kimlik ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 11, 106, 35));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("ID");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 40, 35));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSifre1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSifre1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSifre1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        new Frm_giris().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        if (!String.copyValueOf(txtSifre1.getPassword()).equals(String.copyValueOf(txtSifre2.getPassword()))) {
         JOptionPane.showMessageDialog(null, "Bu şifreler eşleşmiyor. Tekrar denemek ister misiniz?");
                txtSifre1.setText("");
                txtSifre2.setText("");   
        }
        else{
            try {
                
                Connection cn = DriverManager.getConnection("jdbc:derby://localhost:1527/personelIzinTakipi", "app", "app");
                String sql = " INSERT INTO YONETICI (ID,ADI,SOYADI,TC_KIMLIK_NUMARASI,SIFRE) VALUES (?,?,?,?,?)";
                PreparedStatement ps = cn.prepareStatement(sql);
                ps.setInt(1, Integer.parseInt(lblID.getText()));
                ps.setString(2, txtAdi.getText());
                ps.setString(3, txtSoyadi.getText());
                ps.setInt(4, Integer.parseInt(txtTc.getText()));
                ps.setString(5, String.copyValueOf(txtSifre1.getPassword()));
            
                ps.executeUpdate();
                this.dispose();
                new Frm_giris().setVisible(true);
               
            } catch (SQLException ex) {
                Logger.getLogger(frm_YoneticilKayit.class.getName()).log(Level.SEVERE, null, ex);
            }
        


    }//GEN-LAST:event_jButton2ActionPerformed
    }
    private void txtSifre2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSifre2ActionPerformed


    }//GEN-LAST:event_txtSifre2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_YoneticilKayit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_YoneticilKayit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_YoneticilKayit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_YoneticilKayit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_YoneticilKayit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblID;
    private javax.swing.JTextField txtAdi;
    private javax.swing.JPasswordField txtSifre1;
    private javax.swing.JPasswordField txtSifre2;
    private javax.swing.JTextField txtSoyadi;
    private javax.swing.JTextField txtTc;
    // End of variables declaration//GEN-END:variables
}
