/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PersonelPaketi;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author scramblebit
 */
public class frmKayitDegistirme extends javax.swing.JFrame {

    DefaultTableModel dtm = new DefaultTableModel();
    public List<Personel> personeller;

    /**
     * Creates new form frmPersonelEkle
     */
    public frmKayitDegistirme() {
        initComponents();

        jTable1.setModel(dtm);
        dtm.setColumnIdentifiers(new Object[]{"id", "Adi", "Soyadi", "Tc kimlik No", "cinsiyet","giris tarihi", "maas", "calisma suresi", "yillik izin"});
        personelleriYazdir();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtAd = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtSoyad = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTc = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtTelefon = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtMaas = new javax.swing.JTextField();
        RadioErkek = new javax.swing.JRadioButton();
        RadioKadin = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        btnDegistir = new javax.swing.JButton();
        btnDegistir1 = new javax.swing.JButton();
        txtId = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 670, 510));

        jLabel1.setText("Ad");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 78, 27));

        txtAd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAdActionPerformed(evt);
            }
        });
        getContentPane().add(txtAd, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 3, 182, -1));

        jLabel2.setText("Soyad");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 33, 78, 27));

        txtSoyad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoyadActionPerformed(evt);
            }
        });
        getContentPane().add(txtSoyad, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 36, 182, -1));

        jLabel3.setText("TC  No");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 71, 78, 27));

        txtTc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTcActionPerformed(evt);
            }
        });
        getContentPane().add(txtTc, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 74, 180, -1));

        jLabel4.setText(" Giris Tarihi");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 131, 78, 27));

        jLabel5.setText("Telefon No");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 176, 78, 27));

        txtTelefon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonActionPerformed(evt);
            }
        });
        getContentPane().add(txtTelefon, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 179, 182, -1));

        jLabel6.setText("Cinsiyet");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 221, 78, 27));

        jLabel7.setText("gun ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 104, 34, -1));

        jLabel8.setText("ay");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 104, 34, -1));

        jLabel9.setText("yıl");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 104, 42, -1));

        jLabel10.setText("id");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 50, 27));

        txtMaas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaasActionPerformed(evt);
            }
        });
        getContentPane().add(txtMaas, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 176, -1));

        buttonGroup1.add(RadioErkek);
        RadioErkek.setText("Erkek");
        getContentPane().add(RadioErkek, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 223, -1, -1));

        buttonGroup1.add(RadioKadin);
        RadioKadin.setSelected(true);
        RadioKadin.setText("Kadın");
        getContentPane().add(RadioKadin, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 223, -1, -1));

        jLabel13.setText("Maaş");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 74, 27));

        jButton2.setText("geri dön");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, 106, -1));

        btnDegistir.setText("kayıt değiştirme");
        btnDegistir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDegistirActionPerformed(evt);
            }
        });
        getContentPane().add(btnDegistir, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 380, 129, -1));

        btnDegistir1.setText("kayıt silme");
        btnDegistir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDegistir1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnDegistir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 119, -1));

        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });
        getContentPane().add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 176, -1));

        jDateChooser1.setDateFormatString("dd-MM- yyyy");
        getContentPane().add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 170, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAdActionPerformed

    private void txtSoyadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoyadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoyadActionPerformed

    private void txtTcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTcActionPerformed

    private void txtTelefonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonActionPerformed

    private void txtMaasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaasActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
        new frm_personelIslemleri().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnDegistirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDegistirActionPerformed
        if(jTable1.getSelectedRow()==-1){
            JOptionPane.showMessageDialog(this, "bir personel secilmedi");
        }
        else{
        boolean sonucCinsiyet;
        if (RadioErkek.isSelected()) {
            sonucCinsiyet = false;
        } else {
            sonucCinsiyet = true;
        }
        ////
        boolean tcKontrolu = true;

        for (Personel person : personeller) {
            if (person.getTcNo() == Integer.valueOf(txtTc.getText()) && Integer.valueOf(txtTc.getText()) != personeller.get(jTable1.getSelectedRow()).getTcNo()) {
                tcKontrolu = false;
                break;
            }
        }

//        boolean ayniBilgiler = true;
//        for (Personel person : personeller) {
//            if (person.getAdi().equals(txtAd.getText())
//                    && person.getSoyadi().equals(txtSoyad.getText()) && txtTc.getText().equals(String.valueOf(person.getTcNo()))) {
//                if (person.getGirisTarihi().equals(jDateChooser1.getDate()) && txtTelefon.getText().equals(String.valueOf(person.getTelefonNo()))
//                        && person.getCinsiyet().equals(sonucCinsiyet) && txtMaas.getText().equals(String.valueOf(person.getMaas()))) {
//                    ayniBilgiler = false;
//                    break;
//                }
        //}
        if (tcKontrolu) {
            EntityManagerFactory emf = Persistence.createEntityManagerFactory("PersonelIzinTakipiAppDatatbasePU");
            EntityManager em = emf.createEntityManager();
            Query q = em.createQuery("UPDATE  Personel p SET  P.adi=:YAD , P.soyadi=:YSOYAD ,"
                    + "p.tcNo=:YTC,P.girisTarihi=:Y_G_TARIHI,P.telefonNo=:yTAELEFON,P.cinsiyet=:YCINSIYET,P.id=:YID,P.calismaSuresi=:YC_SURESI,p.yillikIzin=:y_izin "
                    + " WHERE  P.id=:ID  ");
            q.setParameter("YAD", txtAd.getText());

            q.setParameter("YSOYAD", txtSoyad.getText());
            q.setParameter("YTC", Integer.parseInt(txtTc.getText()));
            q.setParameter("Y_G_TARIHI", jDateChooser1.getDate());
            q.setParameter("yTAELEFON", Integer.parseInt(txtTelefon.getText()));
            q.setParameter("YCINSIYET", sonucCinsiyet);
            q.setParameter("YID", Integer.parseInt(txtId.getText()));
            q.setParameter("YC_SURESI", getCalismaSuresi());
            q.setParameter("y_izin", YilikIzinHesapla());
            q.setParameter("ID", personeller.get(jTable1.getSelectedRow()).getId());
            em.getTransaction().begin();
            try {
                q.executeUpdate();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "id numarasi baska bir personele aittir");
            }
            em.getTransaction().commit();
         

           personelleriYazdir();
        } else if (!tcKontrolu) {
            JOptionPane.showMessageDialog(this, " TC kimlik numarasi baska bir personele aittir");
        }
        }
    }//GEN-LAST:event_btnDegistirActionPerformed


    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        txtAd.setText(personeller.get(jTable1.getSelectedRow()).getAdi());
        txtSoyad.setText(personeller.get(jTable1.getSelectedRow()).getSoyadi());
        txtTc.setText(personeller.get(jTable1.getSelectedRow()).getTcNo().toString());

        txtTelefon.setText(personeller.get(jTable1.getSelectedRow()).getTelefonNo().toString());
        txtMaas.setText(personeller.get(jTable1.getSelectedRow()).getMaas().toString());
        txtId.setText(personeller.get(jTable1.getSelectedRow()).getId().toString());
        jDateChooser1.setDate(personeller.get(jTable1.getSelectedRow()).getGirisTarihi());
        RadioErkek.setSelected(!personeller.get(jTable1.getSelectedRow()).getCinsiyet());
        RadioKadin.setSelected(personeller.get(jTable1.getSelectedRow()).getCinsiyet());
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnDegistir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDegistir1ActionPerformed
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("PersonelIzinTakipiAppDatatbasePU");
        //
         EntityManager em3 = emf.createEntityManager();
        Query q3 = em3.createQuery("SELECT p FROM Personel p");
        personeller = q3.getResultList();
        //
        // delete personel gunluk izinleri
         
        EntityManager em2 = emf.createEntityManager();
        Query q2 = em2.createQuery("DELETE FROM SaatlikIzin1 s where s.pid=:pId");
        q2.setParameter("pId", personeller.get(jTable1.getSelectedRow()).getId());
        em2.getTransaction().begin();
        q2.executeUpdate();
        em2.getTransaction().commit();
        em2.close();
        
        //
          // delete personel saatlik izinleri
         EntityManager em4 = emf.createEntityManager();
        Query q4 = em4.createQuery("DELETE FROM GunlukIzin g where g.pid=:pId");
        q4.setParameter("pId", personeller.get(jTable1.getSelectedRow()).getId());
        em4.getTransaction().begin();
        q4.executeUpdate();
        em4.getTransaction().commit();
        em4.close();
          //
        EntityManager em = emf.createEntityManager();
        Query q = em.createQuery("DELETE FROM Personel P WHERE  P.id=:YID");
        q.setParameter("YID", personeller.get(jTable1.getSelectedRow()).getId());
        em.getTransaction().begin();
        q.executeUpdate();
        em.getTransaction().commit();
        em.close();
        emf.close();
        
        personelleriYazdir();
        
    }//GEN-LAST:event_btnDegistir1ActionPerformed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed
//    private void personelleriYazdir() {
//        dtm.setRowCount(0);
//        for (Personel p : Personel.personeller) {
//            dtm.addRow(new Object[]{p.sicil_No, p.ad, p.soyad, p.tc_kimlik});
//
//        }

//    private void clear() {
//         txtAd.setText(" ");
//        txtSoyad.setText(" ");
//        txtTc.setText(" ");
//
//        txtYil.setText(" ");
//        txtAdres.setText(" ");
//
//        txtTelefon.setText(" ");
//        txtMaas.setText(" ");
//        jLabel4.setText(" ");
//        jLabel4.setText(String.valueOf(Personel.personeller.size()+ 1) );
//    
    /**
     * @param args the command line arguments
     */
    private void personelleriYazdir() {
        dtm.setRowCount(0);
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("PersonelIzinTakipiAppDatatbasePU");
        EntityManager em = emf.createEntityManager();
        Query q = em.createQuery("SELECT p FROM Personel p");
        personeller = q.getResultList();
        
        for (Personel person : personeller) {
          DateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
         String gun = dateFormat.format(person.getGirisTarihi());
            dtm.addRow(new Object[]{person.getId(), person.getAdi(), person.getSoyadi(), person.getTcNo(),person.getCinsiyet(),gun
              , person.getMaas(), person.getCalismaSuresi(), person.getYillikIzin()});
        }

    }

    public final int getCalismaSuresi() {

        Date date = new Date();

        long diffInMillies = date.getTime() - jDateChooser1.getDate().getTime();

        int calismaSuresi = Integer.valueOf(String.valueOf(diffInMillies / (1000 * 60 * 60 * 24)));

        return calismaSuresi;

    }

    public final int YilikIzinHesapla() {
        int yillikIzin = 0;

        if (getCalismaSuresi() < 1 * 365) {
            yillikIzin = 0;
        } else if (getCalismaSuresi() <= 5 * 365) {
            yillikIzin = 14;
        } else if (getCalismaSuresi() > 5 * 365) {
            yillikIzin = 20;
        }

        return yillikIzin;
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmKayitDegistirme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmKayitDegistirme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmKayitDegistirme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmKayitDegistirme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmKayitDegistirme().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton RadioErkek;
    private javax.swing.JRadioButton RadioKadin;
    private javax.swing.JButton btnDegistir;
    private javax.swing.JButton btnDegistir1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtAd;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtMaas;
    private javax.swing.JTextField txtSoyad;
    private javax.swing.JTextField txtTc;
    private javax.swing.JTextField txtTelefon;
    // End of variables declaration//GEN-END:variables
}
