/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IzinPaketi;

import PersonelPaketi.Personel;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;

import java.util.logging.Level;
import java.util.logging.Logger;

import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author scramblebit
 */
public class frm_izinSilme_degistirme extends javax.swing.JFrame {

    DefaultTableModel dtm = new DefaultTableModel();
    DefaultTableModel dtm2 = new DefaultTableModel();
    /**
     * Creates new form frm_PersonelIzinleri
     */

    public List<Personel> personeller;
    public List<SaatlikIzin1> izinlerS;
    public List<GunlukIzin> izinlerG;

    public frm_izinSilme_degistirme() {
        initComponents();
        jTable1.setModel(dtm);
        jTable2.setModel(dtm2);
        jComboBox1.removeAllItems();

        dtm2.setColumnIdentifiers(new Object[]{"Calisma suresi", "Yillik Izin hakki", "kullanılan izin miktar", "kalan izin miktar", "kullanılan Saat", "kalan Saat"});
        dtm.setColumnIdentifiers(new Object[]{"izin Id", "Başlangıç Tarihi", "Bitiş Tarihi", "Süre", "Tür", "Tür", "Başlangıç Saati", "Bitiş Saati"});
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("PersonelIzinTakipiAppDatatbasePU");
        EntityManager em = emf.createEntityManager();
        Query q = em.createQuery("SELECT P FROM Personel P");
        personeller = q.getResultList();
        for (Personel personel_1 : personeller) {
            jComboBox1.addItem(personel_1.getAdi() + " " + personel_1.getSoyadi());

        }

        jComboBox1.setSelectedIndex(-1);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblTc = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Personel Ad");

        jLabel3.setText("personel Id");

        jLabel4.setText("Tc Kimlik No");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton2.setText("geri don");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });

        jButton1.setText("sil");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("dosyadan silinenleri yazdir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTc, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblID, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(97, 97, 97))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jButton3)
                        .addContainerGap(253, Short.MAX_VALUE))))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblID, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblTc, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new frm_izinIslemleri().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed
    Personel secilen_personel;
    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        // TODO add your handling code here:
        bilgileriYazdir();
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

//
        if (jTable1.getSelectedRow() != -1) {
            // file olusturmak
            try {
                BufferedWriter bw = new BufferedWriter(new FileWriter("C:\\projebP2\\silinenIzinler.txt", true));
                for (int i = 0; i < jTable1.getColumnCount(); i++) {
                    bw.write(dtm.getValueAt(jTable1.getSelectedRow(), i).toString() + "   ");

                }
               // bw.write("personel Id ="+lblID.getText());
                bw.newLine();
                
                bw.close();
            } catch (IOException ex) {
                Logger.getLogger(frm_izinSilme_degistirme.class.getName()).log(Level.SEVERE, null, ex);
            }
            //
            EntityManagerFactory emf = Persistence.createEntityManagerFactory("PersonelIzinTakipiAppDatatbasePU");
            if (dtm.getValueAt(jTable1.getSelectedRow(), 5).toString().equals("(gunluk)")) {
                //

                EntityManager em = emf.createEntityManager();
                Query q = em.createQuery("DELETE from GunlukIzin g  where g.id=:id");
                q.setParameter("id", Integer.valueOf(dtm.getValueAt(jTable1.getSelectedRow(), 0).toString()));
                em.getTransaction().begin();
                q.executeUpdate();

                //
                if (!dtm.getValueAt(jTable1.getSelectedRow(), 4).toString().equals("ucretsiz")) {
                    EntityManager em2 = emf.createEntityManager();
                    Query q2 = em2.createQuery("UPDATE Personel p  set p.kullanilanIzin=:KullanilanIzin, p.kalanIzin=:KalanIzin where p.id=:Id ");
                    Integer YeniKullanilan = secilen_personel.getKullanilanIzin() - Integer.valueOf(dtm.getValueAt(jTable1.getSelectedRow(), 3).toString());
                    q2.setParameter("KullanilanIzin", YeniKullanilan);
                    q2.setParameter("KalanIzin", secilen_personel.getYillikIzin() - YeniKullanilan);
                    q2.setParameter("Id", secilen_personel.getId());
                    em2.getTransaction().begin();
                    q2.executeUpdate();
                    //
                    em2.getTransaction().commit();
                }
                em.getTransaction().commit();

                //
                bilgileriYazdir();

            } else if (dtm.getValueAt(jTable1.getSelectedRow(), 5).toString().equals("(saatlik)")) {
                EntityManager em = emf.createEntityManager();
                Query q = em.createQuery("DELETE from SaatlikIzin1 s  where s.id=:id");
                q.setParameter("id", Integer.valueOf(dtm.getValueAt(jTable1.getSelectedRow(), 0).toString()));
                em.getTransaction().begin();
                q.executeUpdate();
                // update personel bilgileri
                if (!dtm.getValueAt(jTable1.getSelectedRow(), 4).toString().equals("ucretsiz")) {
                    EntityManager em2 = emf.createEntityManager();
                    Query q2 = em2.createQuery("UPDATE Personel p  set p.kullanilanIzin=:KullanilanIzin, p.kalanIzin=:KalanIzin , p.kullanilanSaat=:KullanilanSaat,p.kalanSaat=:KalanSaat WHERE p.id=:Id ");
                    Integer yeniKullanilanSaat = secilen_personel.getKullanilanSaat() - Integer.valueOf(dtm.getValueAt(jTable1.getSelectedRow(), 3).toString());
                    if (yeniKullanilanSaat >= 0) {
                        q2.setParameter("KullanilanIzin", secilen_personel.getKullanilanIzin());//degismez
                        q2.setParameter("KalanIzin", secilen_personel.getKalanIzin());//degismez
                        q2.setParameter("KullanilanSaat", yeniKullanilanSaat);
                        Integer kalanSaat = 7 - yeniKullanilanSaat;
                        if (yeniKullanilanSaat == 0) {
                            kalanSaat = 0;
                        }
                        q2.setParameter("KalanSaat", kalanSaat);
                    } else if (yeniKullanilanSaat < 0) {
                        q2.setParameter("KullanilanIzin", (secilen_personel.getKullanilanIzin() - 1));
                        q2.setParameter("KalanIzin", (secilen_personel.getKalanIzin() + 1));

                        Integer kullanilan = 7 - Integer.valueOf(dtm.getValueAt(jTable1.getSelectedRow(), 3).toString()) + secilen_personel.getKullanilanSaat();
                        q2.setParameter("KullanilanSaat", kullanilan);
                        q2.setParameter("KalanSaat", 7 - kullanilan);

                        //Integer kalan=secilen_personel.getKalanSaat()+Integer.valueOf(dtm.getValueAt(jTable1.getSelectedRow(), 3).toString());
//                    if(kalan>=7)
//                    q2.setParameter("KullanilanSaat", 7-kalan);
//                    q2.setParameter("KalanSaat", kalan);
                    }
                    q2.setParameter("Id", secilen_personel.getId());
                    em2.getTransaction().begin();
                    q2.executeUpdate();

                    //
                    em2.getTransaction().commit();
                }
                em.getTransaction().commit();
                bilgileriYazdir();
            }
        }

 

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        dtm.setRowCount(0);
       int satirSayisi=0;
      
        try (Scanner s = new Scanner(new BufferedReader(new FileReader("C:\\projebP2\\silinenIzinler.txt")))) {

            for (int i = 0; s.hasNextLine(); i++) {
             for (int j = 0; j < jTable1.getColumnCount(); j++) {
                  // dtm.setValueAt(s.next(), i, j);
                  System.out.print(s.next() + "  ");
//                  
             }
               System.out.println("");
                satirSayisi++;
         
            }
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(frm_izinSilme_degistirme.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {

        }
        //jTable1.setModel(dtm);
       //System.out.println(""+satirSayisi);
       
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public void bilgileriYazdir() {
        dtm.setRowCount(0);
        dtm2.setRowCount(0);
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("PersonelIzinTakipiAppDatatbasePU");
        EntityManager em = emf.createEntityManager();
        Query q = em.createQuery("SELECT P FROM Personel P");
        personeller = q.getResultList();
        //
        if (jComboBox1.getSelectedIndex() == -1) {
            lblTc.setText(null);
            lblID.setText(null);
            dtm2.setRowCount(0);
            dtm.setRowCount(0);
        } else {
            lblTc.setText(personeller.get(jComboBox1.getSelectedIndex()).getTcNo().toString());
            lblID.setText(personeller.get(jComboBox1.getSelectedIndex()).getId().toString());
            dtm2.setRowCount(0);
            dtm.setRowCount(0);
            //"Calisma suresi", "Yillik Izin hakki", "kullanılan izin miktar", "kalan izin miktar", "kullanılan Saat", "kalan Saat"});
            secilen_personel = personeller.get(jComboBox1.getSelectedIndex());
            DateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
            // String girisTarihi = dateFormat.format(secilen_personel.getGirisTarihi());
            Integer kontrolluKullanilanIzin = secilen_personel.getKullanilanIzin();
            Integer kontrolluKalanIzin = secilen_personel.getKalanIzin();
            if (secilen_personel.getKullanilanSaat() > 0) {
                kontrolluKullanilanIzin = secilen_personel.getKullanilanIzin() + 1;
                kontrolluKalanIzin = secilen_personel.getKalanIzin() - 1;
            }
            dtm2.addRow(new Object[]{secilen_personel.getCalismaSuresi(), secilen_personel.getYillikIzin(), kontrolluKullanilanIzin, kontrolluKalanIzin, secilen_personel.getKullanilanSaat(), secilen_personel.getKalanSaat()});
            // EntityManagerFactory emf = Persistence.createEntityManagerFactory("PersonelIzinTakipiAppDatatbasePU");
            //saatlik izinler
            EntityManager em2 = emf.createEntityManager();
            Query q2 = em2.createQuery("SELECT s FROM SaatlikIzin1 s");
            izinlerS = q2.getResultList();
            for (SaatlikIzin1 saatlikIzin1 : izinlerS) {
                if (saatlikIzin1.getPid() == secilen_personel.getId()) {
//"izin Id", "Başlangıç Tarihi", "Bitiş Tarihi", "Süre", "Tür", "Başlangıç Saati", "Bitiş Saati"});
                    String Tarih = dateFormat.format(saatlikIzin1.getTarih());

                    dtm.addRow(new Object[]{saatlikIzin1.getId(), Tarih, Tarih, saatlikIzin1.getSure(), saatlikIzin1.getTur(), "(saatlik)", saatlikIzin1.getBasSaat(), saatlikIzin1.getBitSaat()});
                }

            }
            //gunluk iziler
            EntityManager em3 = emf.createEntityManager();
            Query q3 = em3.createQuery("SELECT g FROM GunlukIzin g");
            izinlerG = q3.getResultList();
            for (GunlukIzin gunlukIzin : izinlerG) {
                if (gunlukIzin.getPid() == secilen_personel.getId()) {
//"izin Id", "Başlangıç Tarihi", "Bitiş Tarihi", "Süre", "Tür", "Başlangıç Saati", "Bitiş Saati"});
                    String basTarihi = dateFormat.format(gunlukIzin.getBaslangicTarihi());
                    String bitisTarihi = dateFormat.format(gunlukIzin.getBitisTarihi());

                    dtm.addRow(new Object[]{gunlukIzin.getId(), basTarihi, bitisTarihi, gunlukIzin.getSure(), gunlukIzin.getTur(), "(gunluk)", "-", "-"});
                }

            }

        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_izinSilme_degistirme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_izinSilme_degistirme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_izinSilme_degistirme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_izinSilme_degistirme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_izinSilme_degistirme().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblTc;
    // End of variables declaration//GEN-END:variables
}
