/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IzinPaketi;

import PersonelPaketi.Personel;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.swing.JOptionPane;

/**
 *
 * @author scramblebit
 */
public class frm_yeniIzinEkle extends javax.swing.JFrame {

    public List<Personel> personeller;
    public List<SaatlikIzin1> izinlerS;
    public List<GunlukIzin> izinlerG;
    Integer EnbuyukIdG = 0, EnbuyukIdS = 0;
    Date date = new Date();

    /**
     * Creates new form yeniIzinVerme
     */
    public frm_yeniIzinEkle() {
        initComponents();
        cmbPersonelG.removeAllItems();
        cmbPersonelS.removeAllItems();

        EntityManagerFactory emf = Persistence.createEntityManagerFactory("PersonelIzinTakipiAppDatatbasePU");
        EntityManager em = emf.createEntityManager();
        Query q = em.createQuery("SELECT P FROM Personel P");
        personeller = q.getResultList();
        for (Personel personel_1 : personeller) {
            cmbPersonelG.addItem(personel_1.getAdi() + " " + personel_1.getSoyadi());
            cmbPersonelS.addItem(personel_1.getAdi() + " " + personel_1.getSoyadi());

        }

        cmbPersonelG.setSelectedIndex(-1);
        cmbPersonelS.setSelectedIndex(-1);
        GunlukIzinIdArtir();
        SaatlikIzinIdArtir();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtTcG = new javax.swing.JTextField();
        lblperG = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        lblbitTarihG = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        cmbTurG = new javax.swing.JComboBox<>();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jDateChooserbasG = new com.toedter.calendar.JDateChooser();
        cmbPersonelG = new javax.swing.JComboBox<>();
        jDateChooserbitisG = new com.toedter.calendar.JDateChooser();
        jLabel20 = new javax.swing.JLabel();
        lblIdG = new javax.swing.JLabel();
        lblbasTarihG = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtTc = new javax.swing.JTextField();
        lblperS = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblTarihS = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtBitisSaat = new javax.swing.JTextField();
        lblturS = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cmbTurS = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txtbasSaati = new javax.swing.JTextField();
        jDateChooserS = new com.toedter.calendar.JDateChooser();
        cmbPersonelS = new javax.swing.JComboBox<>();
        lblIdS = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        lblbasSaat = new javax.swing.JLabel();
        lblbitSaat1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setForeground(new java.awt.Color(255, 51, 51));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(477, 497, -1, 32));

        jLabel13.setForeground(new java.awt.Color(255, 51, 51));
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(477, 535, -1, 32));

        jLabel10.setText("TC Kimlik No");

        lblperG.setForeground(new java.awt.Color(255, 51, 51));

        jLabel14.setText("Ad");

        jLabel15.setText("Izin Başlangıç tarihi");

        jLabel16.setForeground(new java.awt.Color(255, 51, 51));

        jLabel17.setText("Izin Bitiş tarihi");

        lblbitTarihG.setForeground(new java.awt.Color(255, 51, 51));

        jLabel19.setText("Izin Türü");

        cmbTurG.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "yillik", "mazeret", "rapor", "ucretsiz" }));
        cmbTurG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTurGActionPerformed(evt);
            }
        });

        jButton7.setText("Yeni izin ekle");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Geri don");
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jDateChooserbasG.setDateFormatString("dd-MM- yyyy");

        cmbPersonelG.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbPersonelG.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbPersonelGItemStateChanged(evt);
            }
        });

        jDateChooserbitisG.setDateFormatString("dd-MM- yyyy");

        jLabel20.setText("id");

        lblbasTarihG.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(206, 206, 206))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtTcG, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cmbPersonelG, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(lblIdG, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(253, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbTurG, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jDateChooserbitisG, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lblbasTarihG, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(lblbitTarihG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jDateChooserbasG, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(324, 324, 324)
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(325, 325, 325)
                            .addComponent(lblperG, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)))
                    .addGap(29, 29, 29)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbPersonelG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTcG, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDateChooserbasG, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jDateChooserbitisG, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                                .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(lblbitTarihG, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbTurG, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblIdG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton8)
                            .addComponent(jButton7))
                        .addGap(61, 61, 61))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblbasTarihG, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lblperG, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(58, 58, 58)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(313, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("gunluk Izin", jPanel3);

        jLabel1.setText("TC Kimlik No");

        lblperS.setForeground(new java.awt.Color(255, 51, 51));

        jLabel3.setText("Ad");

        jLabel5.setText("Izin Başlangıç Saati");

        lblTarihS.setForeground(new java.awt.Color(255, 51, 51));

        jLabel7.setText("Izin Bitiş Saati");

        lblturS.setForeground(new java.awt.Color(255, 51, 51));

        jLabel9.setText("Izin Türü");

        cmbTurS.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "yillik", "mazeret", "rapor", "ucretsiz" }));

        jButton1.setText("Yeni izin ekle");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Geri don");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel12.setText("Izin Tarihi");

        jDateChooserS.setDateFormatString("dd-MM- yyyy");

        cmbPersonelS.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbPersonelS.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbPersonelSItemStateChanged(evt);
            }
        });

        jLabel22.setText("id");

        lblbasSaat.setForeground(new java.awt.Color(255, 51, 51));

        lblbitSaat1.setForeground(new java.awt.Color(255, 51, 51));

        jLabel2.setText("SS:dd:ss");

        jLabel6.setText("SS:dd:ss");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtTc, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cmbPersonelS, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbTurS, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblIdS, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jDateChooserS, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTarihS, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblperS, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                            .addComponent(lblturS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtBitisSaat, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtbasSaati, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblbasSaat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblbitSaat1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmbPersonelS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblperS, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTc, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jDateChooserS, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTarihS, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblbasSaat, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtbasSaati, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(lblbitSaat1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBitisSaat, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbTurS, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblturS, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIdS, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(63, 63, 63))
        );

        jTabbedPane1.addTab("saatlik Izin", jPanel1);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new frm_izinIslemleri().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        this.dispose();
        new frm_izinIslemleri().setVisible(true);
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        boolean sonuc = true;
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("PersonelIzinTakipiAppDatatbasePU");
        // update personel bilgileri
        EntityManager em3 = emf.createEntityManager();
        Query q3 = em3.createQuery("SELECT P FROM Personel P");
        personeller = q3.getResultList();
        //
        Personel secilen_personel = personeller.get(cmbPersonelS.getSelectedIndex());
        if (cmbPersonelS.getSelectedIndex() == -1) {
            lblperS.setVisible(true);
            lblperS.setText("personel secilmedi");
            sonuc = false;
        }
        ////////
        if (jDateChooserS.getDate() == null || jDateChooserS.getDate().before(date)) {
            lblTarihS.setVisible(true);
            lblTarihS.setText("Geçerli Bir tarih Giriniz");
            sonuc = false;
        }
        ///

        String desenSaat = "\\b([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]\\b";
        String saat1 = txtbasSaati.getText();
        Pattern p = Pattern.compile(desenSaat);
        Matcher m = p.matcher(saat1);
        boolean sonuc1 = false;
        while (m.find()) {
            sonuc1 = true;
        }
        if (!sonuc1) {
            lblbasSaat.setVisible(true);
            lblbasSaat.setText("Geçerli Bir saat Giriniz");
        }
        //bitis saati
        String saat2 = txtBitisSaat.getText();

        Matcher m2 = p.matcher(saat2);
        boolean sonuc2 = false;
        while (m2.find()) {

            sonuc2 = true;
        }
        if (!sonuc2) {
            lblbasSaat.setVisible(true);

            lblbitSaat1.setText("Geçerli Bir saat Giriniz");
        }
        //yillik izin kontrulu
        Integer sure = 0;
        String basSaat = txtbasSaati.getText();
        String bitisSaat = txtBitisSaat.getText();
        try {

            SimpleDateFormat format = new SimpleDateFormat("HH:mm:ss");

            Date time1 = format.parse(basSaat);
            Date time2 = format.parse(bitisSaat);
            long dif = time2.getTime() - time1.getTime();
            sure = Integer.valueOf(String.valueOf(TimeUnit.MILLISECONDS.toHours(dif)));
        } catch (ParseException ex) {
            //Logger.getLogger(frm_yeniIzinEkle.class.getName()).log(Level.SEVERE, null, ex);
               lblbitSaat1.setText("Geçerli Bir saat Giriniz");
        }
//        //
//        (person.kalan_izin_MiktarHesapla() == 0
//                            && (person.kulllanilanSaat + Integer.parseInt(lblSure1.getText())) <= 7
        boolean sonuc3 = false;
        if (secilen_personel.getKalanIzin() > 1
                || String.valueOf(cmbTurS.getSelectedItem()).equals("ucretsiz")
                || (secilen_personel.getKalanIzin() == 1 && (secilen_personel.getKullanilanSaat() + sure) <= 7)) {
            sonuc3 = true;
            // String.valueOf(cmbTurS.getSelectedItem().equals("ucretsiz")   
        }
       // SaatlikIzinTekrarlamaKontrolu(secilen_personel);
        if (sonuc == sonuc1 == sonuc2 == sonuc3 == SaatlikIzinTekrarlamaKontrolu(secilen_personel) == true) {
            lblbasSaat.setVisible(false);
            lblbasSaat.setVisible(false);
            lblTarihS.setVisible(false);
            lblperS.setVisible(false);
            //sure hesaplamak

            if (sure < 1) {
                lblbitSaat1.setVisible(true);
                lblbitSaat1.setText("girdiginiz bilgilere dikkat ediniz");
            } else if (sure >= 7) {
                lblbitSaat1.setVisible(true);
                lblbitSaat1.setText("gunluk izin verin");
            } else {
                lblbitSaat1.setVisible(false);
                EntityManager em = emf.createEntityManager();
                em.getTransaction().begin();

                //Integer id, Integer pid, String tur, Date tarih, String basSaat, String bitSaat, Integer sure
                em.persist(new SaatlikIzin1(EnbuyukIdS, secilen_personel.getId(), cmbTurS.getSelectedItem().toString(), jDateChooserS.getDate(), basSaat, bitisSaat, sure));
                em.getTransaction().commit();
                // personel bilgileri degistirmek
                if (!String.valueOf(cmbTurS.getSelectedItem()).equals("ucretsiz")) {
                    EntityManager em2 = emf.createEntityManager();
                    Query q = em2.createQuery("UPDATE Personel P SET P.kullanilanSaat=:KullanilanSaat, p.kalanSaat=:KalanSaat,p.kullanilanIzin=:KullanilanIzin,p.kalanIzin=:KalanIzin where p.id=:Id");
                    Integer KullanilanSaat = 0, kalanSaat = 0, KalanIzin = 0, KullanilanIzin = 0;
                    Integer toplamSure = sure + secilen_personel.getKullanilanSaat();
                    if (toplamSure >= 7) {

                        if ((toplamSure - 7) == 0) {
                            kalanSaat = 0;
                        } else {
                            kalanSaat = 7 - (toplamSure - 7);
                        }
                        KullanilanSaat = toplamSure - 7;

                        KullanilanIzin = secilen_personel.getKullanilanIzin() + 1;
                        KalanIzin = secilen_personel.getKalanIzin() - 1;

                    } else if (toplamSure < 7) {

                        KullanilanSaat = toplamSure;
                        kalanSaat = 7 - toplamSure;
                        KullanilanIzin = secilen_personel.getKullanilanIzin();
                        KalanIzin = secilen_personel.getKalanIzin();
                    }
                    q.setParameter("KullanilanSaat", KullanilanSaat);
                    q.setParameter("KalanSaat", kalanSaat);
                    q.setParameter("KullanilanIzin", KullanilanIzin);
                    q.setParameter("KalanIzin", KalanIzin);
                    q.setParameter("Id", secilen_personel.getId());

                    em2.getTransaction().begin();
                    q.executeUpdate();
                    em2.getTransaction().commit();
                }
                clear_SaatlikIzin();

            }

        } else if (!sonuc3) {
            JOptionPane.showMessageDialog(this, "yillik izin haki bittmis, ucretsiz izin verilebilir");
        } else if (!SaatlikIzinTekrarlamaKontrolu(secilen_personel)) {
            JOptionPane.showMessageDialog(this, "Izin daha once kaydedildi");
        }
          

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new frm_izinIslemleri().setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8MouseClicked

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        // update personel listesi
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("PersonelIzinTakipiAppDatatbasePU");
        EntityManager em2 = emf.createEntityManager();
        Query q = em2.createQuery("SELECT P FROM Personel P");
        personeller = q.getResultList();
        //
        boolean sonuc4 = true;
        if (cmbPersonelG.getSelectedIndex() == -1) {
            lblperG.setVisible(true);
            lblperG.setText("personel secilmedi");
            sonuc4 = false;
        }
        if (jDateChooserbasG.getDate() == null) {
            lblbasTarihG.setVisible(true);
            lblbasTarihG.setText("tarih secilmedi");
            sonuc4 = false;
        }
        if (jDateChooserbitisG.getDate() == null) {
            lblbitTarihG.setVisible(true);
            lblbitTarihG.setText("tarih secilmedi");
            sonuc4 = false;
        } // sure hesaplamak
        long diffInMillies = jDateChooserbitisG.getDate().getTime() - jDateChooserbasG.getDate().getTime();

        Integer sure = Integer.valueOf(String.valueOf(diffInMillies / (1000 * 60 * 60 * 24)));

        if (sure < 1 || jDateChooserbitisG.getDate().before(date)
                || jDateChooserbitisG.getDate().before(jDateChooserbasG.getDate())) {
            lblbitTarihG.setVisible(true);///
            lblbitTarihG.setText("girdiginiz bilgilere dikkat ediniz ! ");
            sonuc4 = false;
        }
        if (jDateChooserbasG.getDate().before(date)) {
            lblbasTarihG.setVisible(true);
            lblbasTarihG.setText("girdiginiz bilgilere dikkat ediniz  ");
            sonuc4 = false;

        } else if (sonuc4) {
            Personel secilen_personel = personeller.get(cmbPersonelG.getSelectedIndex());
            lblperG.setVisible(false);
            lblbasTarihG.setVisible(false);
            lblbitTarihG.setVisible(false);

            //yillik Izin kontroli
            boolean sonuc3 = false;
            if ((secilen_personel.getKalanIzin() - sure) > 0
                    || ((secilen_personel.getKalanIzin() - sure) == 0 && secilen_personel.getKullanilanSaat() == 0)
                    || String.valueOf(cmbTurG.getSelectedItem()).equals("ucretsiz")) {

                sonuc3 = true;

            }
            Integer kulanilan = secilen_personel.getKullanilanIzin() + sure;
//             if(kulanilan<0){
//                sonuc4 = false; 
//             }
            if (sonuc4 && sonuc3 && gunlukIzinTekrarlamaKontrolu(secilen_personel)) {
                //Integer id, Integer pid, String tur, Date baslangicTarihi, Date bitisTarihi, Integer sure

                EntityManager em = emf.createEntityManager();
                em.getTransaction().begin();
                em.persist(new GunlukIzin(
                        EnbuyukIdG,
                        personeller.get(cmbPersonelG.getSelectedIndex()).getId(),
                        cmbTurG.getSelectedItem().toString(),
                        jDateChooserbasG.getDate(),
                        jDateChooserbitisG.getDate(),
                        sure
                ));
                em.getTransaction().commit();

                if (!String.valueOf(cmbTurG.getSelectedItem()).equals("ucretsiz")) {
                    EntityManager em3 = emf.createEntityManager();
                    Query q2 = em3.createQuery("UPDATE Personel p SET P.kullanilanIzin=:kullanilan_izin, p.kalanIzin=:kalan_izin WHERE P.id=:PID ");

                    q2.setParameter("kullanilan_izin", kulanilan);
                    q2.setParameter("kalan_izin", secilen_personel.getYillikIzin() - kulanilan);
                    q2.setParameter("PID", secilen_personel.getId());
                    em3.getTransaction().begin();
                    q2.executeUpdate();
                    em3.getTransaction().commit();
                }
                //
                clear_gunlukIzin();

                //hareket Yontemi
            } else if (!sonuc3) {
                JOptionPane.showMessageDialog(this, "yillik izin haki bittmis, ucretsiz izin verilebilir");
            } else if (!gunlukIzinTekrarlamaKontrolu(secilen_personel)) {
                JOptionPane.showMessageDialog(this, "Izin daha once kaydedildi");
            }

        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void cmbPersonelGItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbPersonelGItemStateChanged
        // TODO add your handling code here:
        if (cmbPersonelG.getSelectedIndex() == -1) {
            txtTcG.setText(null);
        } else {
            txtTcG.setText(personeller.get(cmbPersonelG.getSelectedIndex()).getTcNo().toString());
        }
    }//GEN-LAST:event_cmbPersonelGItemStateChanged

    private void cmbPersonelSItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbPersonelSItemStateChanged
        // TODO add your handling code here:
        if (cmbPersonelS.getSelectedIndex() == -1) {
            txtTc.setText(null);
        } else {
            txtTc.setText(personeller.get(cmbPersonelS.getSelectedIndex()).getTcNo().toString());
        }
    }//GEN-LAST:event_cmbPersonelSItemStateChanged

    private void cmbTurGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTurGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTurGActionPerformed

    /**
     * @param args the command line arguments
     */
    public void clear_gunlukIzin() {
        cmbPersonelG.setSelectedIndex(-1);
        jDateChooserbasG.setDate(null);
        jDateChooserbitisG.setDate(null);
        GunlukIzinIdArtir();
    }

    public void clear_SaatlikIzin() {
        cmbPersonelS.setSelectedIndex(-1);
        jDateChooserS.setDate(null);
        txtBitisSaat.setText(null);
        txtbasSaati.setText(null);
        SaatlikIzinIdArtir();
    }

    public void GunlukIzinIdArtir() {
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("PersonelIzinTakipiAppDatatbasePU");
        EntityManager em2 = emf.createEntityManager();
        Query q2 = em2.createQuery("SELECT g FROM GunlukIzin g");
        izinlerG = q2.getResultList();
        for (GunlukIzin gunlukIzin : izinlerG) {
            if (EnbuyukIdG < gunlukIzin.getId()) {
                EnbuyukIdG = gunlukIzin.getId();
            }
        }
        lblIdG.setText(String.valueOf(++EnbuyukIdG));
    }

    public void SaatlikIzinIdArtir() {
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("PersonelIzinTakipiAppDatatbasePU");
        EntityManager em2 = emf.createEntityManager();
        Query q2 = em2.createQuery("SELECT s FROM SaatlikIzin1 s");
        izinlerS = q2.getResultList();
        for (SaatlikIzin1 saatlikIzin : izinlerS) {
            if (EnbuyukIdS < saatlikIzin.getId()) {
                EnbuyukIdS = saatlikIzin.getId();
            }
        }
        lblIdS.setText(String.valueOf(++EnbuyukIdS));
    }

    public boolean gunlukIzinTekrarlamaKontrolu(Personel secilen_personel) {
        boolean sonuc = true;
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("PersonelIzinTakipiAppDatatbasePU");
        EntityManager em = emf.createEntityManager();
        Query q = em.createQuery("SELECT g FROM GunlukIzin g");
        izinlerG = q.getResultList();
        for (GunlukIzin gunlukIzin : izinlerG) {
            if (gunlukIzin.getPid() == secilen_personel.getId()) {
                if (jDateChooserbasG.getDate().after(gunlukIzin.getBaslangicTarihi())
                   && jDateChooserbitisG.getDate().before(gunlukIzin.getBitisTarihi())) {
                    sonuc = false;
                    break;
                } else if (jDateChooserbasG.getDate().before(gunlukIzin.getBaslangicTarihi())
                        && jDateChooserbitisG.getDate().after(gunlukIzin.getBaslangicTarihi())) {
                    sonuc = false;
                    break;
                } else if (jDateChooserbasG.getDate().before(gunlukIzin.getBitisTarihi())
                        && jDateChooserbitisG.getDate().after(gunlukIzin.getBitisTarihi())) {
                    sonuc = false;
                    break;
                } else if (jDateChooserbasG.getDate().before(gunlukIzin.getBaslangicTarihi())
                        && jDateChooserbitisG.getDate().after(gunlukIzin.getBitisTarihi())) {
                    sonuc = false;
                    break;
                } else if (jDateChooserbasG.getDate().equals(gunlukIzin.getBaslangicTarihi())
                        || jDateChooserbasG.getDate().equals(gunlukIzin.getBitisTarihi())
                       || jDateChooserbitisG.getDate().equals(gunlukIzin.getBaslangicTarihi())
                       || jDateChooserbitisG.getDate().equals(gunlukIzin.getBitisTarihi())) {
                    sonuc = false;//*
                    break;
                }
            }

        }
        ////////////
        EntityManager em2 = emf.createEntityManager();
        Query q2 = em2.createQuery("SELECT s FROM SaatlikIzin1 s");
        izinlerS = q2.getResultList();
        for (SaatlikIzin1 saatlikIzin : izinlerS) {
            if (saatlikIzin.getPid() == secilen_personel.getId()) {
                if (saatlikIzin.getTarih().equals(jDateChooserbasG.getDate())
                   || saatlikIzin.getTarih().equals(jDateChooserbitisG.getDate())) {
                    sonuc = false;
                    break;
                } else if (jDateChooserbasG.getDate().before(saatlikIzin.getTarih())
                        && jDateChooserbitisG.getDate().after(saatlikIzin.getTarih())) {
                    sonuc = false;
                    break;
                }
            }
        }
        return sonuc;

    }

    public boolean SaatlikIzinTekrarlamaKontrolu(Personel secilen_personel) {
        boolean sonuc = true;
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("PersonelIzinTakipiAppDatatbasePU");
        EntityManager em = emf.createEntityManager();
        Query q = em.createQuery("SELECT g FROM GunlukIzin g");
        izinlerG = q.getResultList();
        for (GunlukIzin gunlukIzin : izinlerG) {
            if (gunlukIzin.getPid() == secilen_personel.getId()){
             
                  if (jDateChooserS.getDate().equals(gunlukIzin.getBitisTarihi())
                    ||jDateChooserS.getDate().equals(gunlukIzin.getBaslangicTarihi())) {
                    sonuc = false;//sorun var
                    break;
                }
                
               else if (jDateChooserS.getDate().after(gunlukIzin.getBaslangicTarihi())
                       && jDateChooserS.getDate().before(gunlukIzin.getBitisTarihi())) {
                    sonuc = false;
                    break;
                }
            }

        }
        ////////////
        EntityManager em2 = emf.createEntityManager();
        Query q2 = em2.createQuery("SELECT s FROM SaatlikIzin1 s");
        izinlerS = q2.getResultList();
        for (SaatlikIzin1 saatlikIzin : izinlerS) {
            if (saatlikIzin.getPid() == secilen_personel.getId()) {
                if (saatlikIzin.getTarih().equals(jDateChooserS.getDate())) {
                    sonuc = false;
                    break;
                }

            }
        }
        return sonuc;

    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_yeniIzinEkle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_yeniIzinEkle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_yeniIzinEkle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_yeniIzinEkle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_yeniIzinEkle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbPersonelG;
    private javax.swing.JComboBox<String> cmbPersonelS;
    private javax.swing.JComboBox<String> cmbTurG;
    private javax.swing.JComboBox<String> cmbTurS;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private com.toedter.calendar.JDateChooser jDateChooserS;
    private com.toedter.calendar.JDateChooser jDateChooserbasG;
    private com.toedter.calendar.JDateChooser jDateChooserbitisG;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblIdG;
    private javax.swing.JLabel lblIdS;
    private javax.swing.JLabel lblTarihS;
    private javax.swing.JLabel lblbasSaat;
    private javax.swing.JLabel lblbasTarihG;
    private javax.swing.JLabel lblbitSaat1;
    private javax.swing.JLabel lblbitTarihG;
    private javax.swing.JLabel lblperG;
    private javax.swing.JLabel lblperS;
    private javax.swing.JLabel lblturS;
    private javax.swing.JTextField txtBitisSaat;
    private javax.swing.JTextField txtTc;
    private javax.swing.JTextField txtTcG;
    private javax.swing.JTextField txtbasSaati;
    // End of variables declaration//GEN-END:variables
}
